a='U_Net'
python main.py --model_type=$a
#a='MixU_Net'
#python main.py --model_type=$a
#a='R2U_Net'
#python main.py --model_type=$a
#a='MixR2U_Net'
#python main.py --model_type=$a
#a='AttU_Net'
#python main.py --model_type=$a
#a='MixAttU_Net'
#python main.py --model_type=$a
#a='R2AttU_Net'
#python main.py --model_type=$a
#a='MixR2AttU_Net'
#python main.py --model_type=$a
